# Adaptation of WezTerm colors to Alacritty (Dark Theme)

[[colors.indexed_colors]]
index = 16
color = "#9e97d0" # ca: purple

[[colors.indexed_colors]]
index = 17
color = "#c58ea7" # ia: pink

[colors.bright]
black = "#3f3b3e"   # gr: dark gray
blue = "#665E7A"    # vb: dark blue
cyan = "#c58ea7"    # ia: cyan (pink)
green = "#878fb9"   # va: green (blue)
magenta = "#9e97d0" # ca: magenta
red = "#c58ea7"     # ia: red
white = "#c5a3a9"   # na: white
yellow = "#9e97d0"  # ca: yellow (purple)

[colors.cursor]
cursor = "#9e97d0" # ca: purple
text = "#c5a3a9"   # na: text

[colors.normal]
black = "#1c1a1c"   # bl: black background
blue = "#665E7A"    # vb: dark blue
cyan = "#c58ea7"    # ia: cyan (pink)
green = "#878fb9"   # va: green (blue)
magenta = "#9e97d0" # ca: magenta
red = "#c58ea7"     # ia: red
white = "#c5a3a9"   # na: light text
yellow = "#9e97d0"  # ca: yellow (purple)

[colors.primary]
background = "#1c1a1c" # bl: background
foreground = "#786577" # na: text

[colors.selection]
background = "#3f3b3e" # gr: gray
text = "#c5a3a9"       # na: text

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 16

[font.normal]
family = "IosevkaTerm NF"

[window]
option_as_alt = "Both"
opacity = 0.96

[env]
TERM = "xterm-256color"
